app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, TextAreaField, SelectField, RadioField, SubmitField
from wtforms.validators import Required, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from flask_pagedown.fields import PageDownField 

class PostForm(FlaskForm):
    alias = TextField('Alias', validators=[Required()])
    title = TextField("Title", validators=[Required()])
    content = PageDownField("What's on your mind?", validators=[Required()])
    tags = TextField('Tags')
    category = SelectField('Category', coerce=int, choices=[('0', 'default')])
    submit = SubmitField("Publish")

class CategoryForm(FlaskForm):
    alias = TextField('Alias', validators=[Required()])
    name = TextField("Name", validators=[Required()])
    submit = SubmitField("Publish")

class TagForm(FlaskForm):
    alias = TextField('Alias', validators=[Required()])
    name = TextField("Name", validators=[Required()])
    submit = SubmitField("Publish")

app/dashboard/__init__.py
from flask import Blueprint

dashboard = Blueprint('dashboard', __name__)

from . import views

app/dashboard/views.py
from flask import render_template, redirect, url_for, abort, session
from . import dashboard
from .. import db
from .forms import PostForm, CategoryForm, TagForm
from ..models import Post, Tag, Category
from flask_login import current_user, login_required
import re
from config import Config, NavigationItemEnum


@dashboard.route('/', methods=['GET', 'POST'])
@login_required
def index():
    Config.CURRENT_NAVIGATION_ITEM = NavigationItemEnum.DASHBOARD
    form = PostForm()
    form.category.choices = [(c.id, c.name) for c in Category.query.order_by('name')]
    if form.validate_on_submit():
        entry = Post(alias=form.alias.data,
                     title=form.title.data,
                     content=form.content.data,
                     author_id=current_user.id)
        entry.category_id = form.category.data
        tags = re.split(';|；|,|，', form.tags.data)
        for tag in tags:
            tag = tag.strip()
            t = Tag.query.filter_by(name=tag).first()
            if not t:
                a = tag.split()
                formata = []
                for b in a:
                    b = b.strip()
                    b = b.replace('.', 'dot')
                    formata.append(b)
                alias = '-'.join(formata)
                new_tag = Tag(name=tag, alias=alias)
                entry.related_tags.append(new_tag)
            else:
                entry.related_tags.append(t)
        db.session.add(entry)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('dashboard/index.html', form=form)

@dashboard.route('/categories', methods=['GET', 'POST'])
@login_required
def categories():
    Config.CURRENT_NAVIGATION_ITEM = NavigationItemEnum.DASHBOARD    
    form = CategoryForm()
    if form.validate_on_submit():
        cat = Category(alias=form.alias.data, name=form.name.data)
        db.session.add(cat)
        db.session.commit()
        return redirect(url_for('dashboard.categories'))
    categories = Category.query.all()
    return render_template('dashboard/categories.html', form=form, categories=categories)

@dashboard.route('/tags', methods=['GET', 'POST'])
@login_required
def tags():
    Config.CURRENT_NAVIGATION_ITEM = NavigationItemEnum.DASHBOARD
    form = TagForm()
    if form.validate_on_submit():
        tag = Tag(alias=form.alias.data, name=form.name.data)
        db.session.add(tag)
        db.session.commit()
        return redirect(url_for('dashboard.tags'))
    tags = Tag.query.all()
    return render_template('dashboard/tags.html', form=form, tags=tags)

app/templates/dashboard/categories.html
{% extends "base.html" %}

{% block title %}Jiuwen's Blog - Categories{% endblock %}

{% block page_content %}
<div class="page-header">
  <h3>Manage All Categories&nbsp;<span class="badge">{{ categories | length }}</span></h3>
</div>

{% if current_user.is_authenticated %}
<div class="panel panel-primary comments-panel">
    <div class="panel-heading comments-head"><i class="fa fa-plus" aria-hidden="true"></i> Add Category</div>
    <div class="panel-body">
        <form action="{{ url_for('dashboard.categories') }}" method=post>
            {{ form.hidden_tag() }}
            <div class="form-group">
                <!--<label for="name">{{ form.name.label }}</label>-->
                {{ form.name(id='name', class='form-control', type='text', placeholder='Category Name') }}
            </div>
            <div class="form-group">
                <!--<label for="alias">{{ form.alias.label }}</label>-->
                {{ form.alias(id='alias', class='form-control', type='text', placeholder='Category Alias') }}
            </div>
            {{ form.submit(type="submit", class="btn btn-primary btn-block") }}
        </form>
    </div>
</div>
{% endif %}

<ul class="common-list">
{% for category in categories %}
    <li>
        <div class="tag-item-group">
            <div class="tag-item-btn">
                <a href="{{ url_for('main.category', category_alias=category.alias) }}">
                    {{ category.name }}
                </a>
            </div>
            <div class="tag-item-count">
                <a href="{{ url_for('main.category', category_alias=category.alias) }}">
                    {{ category.related_posts.count() }}
                </a>
            </div>
        </div>
    </li>
{% endfor %}
</ul>
{% endblock %}

app/templates/dashboard/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Jiuwen's Blog - Dashboard{% endblock %}


{% block page_content %}
<div class="page-header">
  <h3><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Write ......</h3>
</div>
{% if current_user.is_authenticated %}
    <form action="{{ url_for('dashboard.index') }}" method=post>
        {{ form.hidden_tag() }}
        <div class="form-group">
            <!--<label for="alias">{{ form.alias.label }}</label>-->
            {{ form.alias(id='alias', class='form-control', type='text', placeholder='Alias') }}
        </div>
        <div class="form-group">
            <!--<label for="title">{{ form.title.label }}</label>-->
            {{ form.title(id='title', class='form-control', type='text', placeholder='Title') }}
        </div>
        <div class="form-group">
            {{ form.content(class='form-control', type='textarea', rows='13', placeholder="What's on your mind?") }}
            {{ pagedown.include_pagedown() }}
        </div>
        <div class="form-group">
            <!--<label for="tags">{{ form.tags.label }}</label>-->
            {{ form.tags(id='tags', class='form-control', type='text', placeholder='Tags') }}
        </div>
        <div class="form-group">
            {{ form.category(id='category', class='form-control', placeholder='Category') }}
        </div>
        {{ form.submit(type="submit", class="btn btn-primary btn-lg btn-block") }}
    </form>
{% endif %}

{% endblock %}

app/templates/dashboard/tags.html
{% extends "base.html" %}

{% block title %}Jiuwen's Blog - Tags{% endblock %}

{% block page_content %}
<div class="page-header">
  <h3>Manage All Tags&nbsp;<span class="badge">{{ tags | length }}</span></h3>
</div>

{% if current_user.is_authenticated %}
<div class="panel panel-primary comments-panel">
    <div class="panel-heading comments-head"><i class="fa fa-plus" aria-hidden="true"></i> Add Tag</div>
    <div class="panel-body">
        <form action="{{ url_for('dashboard.tags') }}" method=post>
            {{ form.hidden_tag() }}
            <div class="form-group">
                <!--<label for="name">{{ form.name.label }}</label>-->
                {{ form.name(id='name', class='form-control', type='text', placeholder='Tag Name') }}
            </div>
            <div class="form-group">
                <!--<label for="alias">{{ form.alias.label }}</label>-->
                {{ form.alias(id='alias', class='form-control', type='text', placeholder='Tag Alias') }}
            </div>
            {{ form.submit(type="submit", class="btn btn-primary btn-block") }}
        </form>
    </div>
</div>
{% endif %}

<ul class="common-list">
{% for tag in tags %}
    <li>
        <div class="tag-item-group">
            <div class="tag-item-btn">
                <a href="{{ url_for('main.tag', tag_alias=tag.alias) }}">
                    {{ tag.name }}
                </a>
            </div>
            <div class="tag-item-count">
                <a href="{{ url_for('main.tag', tag_alias=tag.alias) }}">
                    {{ tag.related_posts.count() }}
                </a>
            </div>
        </div>
    </li>
{% endfor %}
</ul>
{% endblock %}